'use strict';
const fs=require('fs'),path=require('path');const root=path.resolve(__dirname,'../../../../..');const identity=require('./CANDIDATE.json');const prior=JSON.parse(fs.readFileSync(path.join(__dirname,'private/review-result.json')));
process.env.MERCURY_HARNESS_TREE=identity.harness;require('../../2026-09-29/mercury-source-identity/fixtures/candidate-loader.cjs');
const bridge=path.join(root,'trai_brain/mercury-bridge');const {runReviewRechecks,createProviderAudit}=require(path.join(bridge,'ask'));const {createToolAdapter}=require(path.join(bridge,'tool-adapter'));const {createMercuryLlmClient}=require(path.join(bridge,'llm-client'));const config=require(path.join(bridge,'config'));
const snapshot=path.join(__dirname,'private/ledger/2026-10-01T18-41-52-380Z-2159373-11e582678932/source-ZOV4Vs');
const query=fs.readFileSync(path.join(__dirname,'private/review-prompt.txt'),'utf8')+'\n\nSubstantive recheck on the SAME selected tree '+identity.candidate+'. Your previous complete answer follows:\n'+prior.answer+'\n\nKimi independently supplied this complete adjudication:\n'+prior.reviewerPanel.seats.find(s=>s.id==='kimi').answer+'\n\nResolve the concrete disagreement against the actual producers and consumers. In particular inspect ConfigLoader maDynamicSRConfidenceReplacementProblem and EDITABLE_SETTINGS and their publication paths, rather than inferring missing validation from the module assignment alone. Preserve any supported findings. Do not add a runtime guard to compensate for a producer you have not traced. Local exact-source integration and cap fixtures passed but their contents are not supplied in this call; do not claim to have read them. Full source tools remain available; no iteration limit.';
fs.writeFileSync(path.join(__dirname,'private/recheck-prompt.txt'),query);
const runId=new Date().toISOString()+'-ma-substantive-recheck';
runReviewRechecks({prompts:[query],client:createMercuryLlmClient({systemPrompt:config.AGENTIC_SYSTEM_PROMPT}),toolAdapter:createToolAdapter({repoRoot:snapshot,gitRepoRoot:root,reviewSource:{tree:identity.candidate,baseTree:'fb0b7b2c6533a0c263e784e00880924c4388f695'},mongoStore:null}),maxIterations:null,maxTokens:7750,verbose:true,evidenceSources:[],createProviderAudit:stage=>createProviderAudit(stage,{repoRoot:root,rawRunId:runId})}).then(result=>{fs.writeFileSync(path.join(__dirname,'private/recheck-result.json'),JSON.stringify({identity,runId,result},null,2));console.log(JSON.stringify(result.rechecks.map(r=>({termination:r.termination,answer:r.answer}))));}).catch(e=>{console.error(e.stack);process.exitCode=1;});
