'use strict';
const fs=require('fs'),path=require('path');const root=path.resolve(__dirname,'../../../../..');const identity=require('./CANDIDATE.json');const prior=JSON.parse(fs.readFileSync(path.join(__dirname,'private/review-result.json')));
process.env.MERCURY_HARNESS_TREE=identity.harness;require('../../2026-09-29/mercury-source-identity/fixtures/candidate-loader.cjs');
const bridge=path.join(root,'trai_brain/mercury-bridge');const {runReviewRechecks,createProviderAudit}=require(path.join(bridge,'ask'));const {createToolAdapter}=require(path.join(bridge,'tool-adapter'));const {createMercuryLlmClient}=require(path.join(bridge,'llm-client'));const config=require(path.join(bridge,'config'));
const snapshot=path.join(__dirname,'private/ledger/2026-10-01T20-44-36-259Z-2249852-e92d9a1cd1ad/source-FZVTUM');
const query=fs.readFileSync(path.join(__dirname,'private/review-prompt.txt'),'utf8')+'\n\nSubstantive same-source recheck. Your complete original answer:\n'+prior.answer+'\n\nKimi complete independent adjudication:\n'+prior.reviewerPanel.seats.find(s=>s.id==='kimi').answer+'\n\nResolve the disputed cached-instance claim by tracing StrategyOrchestrator evaluation at2197-2204 through TimeSeriesMomentum.evaluate/configure at99-112 and saved/forced snapshot publication. Preserve any supported finding. Do not infer that cached identity means immutable configuration. Complete actual host behavior receipt follows (exact candidate; no source patches applied):\n'+fs.readFileSync(path.join(__dirname,'delivery/behavior.json'),'utf8');
fs.writeFileSync(path.join(__dirname,'private/recheck-prompt.txt'),query);
const runId=new Date().toISOString()+'-tsm-substantive-recheck';
runReviewRechecks({prompts:[query],client:createMercuryLlmClient({systemPrompt:config.AGENTIC_SYSTEM_PROMPT}),toolAdapter:createToolAdapter({repoRoot:snapshot,gitRepoRoot:root,reviewSource:{tree:identity.candidate,baseTree:require('child_process').execFileSync('git',['rev-parse',identity.base+'^{tree}'],{cwd:root,encoding:'utf8'}).trim()},mongoStore:null}),maxIterations:null,maxTokens:7750,verbose:true,evidenceSources:[],createProviderAudit:stage=>createProviderAudit(stage,{repoRoot:root,rawRunId:runId})}).then(result=>{fs.writeFileSync(path.join(__dirname,'private/recheck-result.json'),JSON.stringify({identity,runId,result},null,2));console.log(JSON.stringify(result.rechecks.map(r=>({termination:r.termination,answer:r.answer}))));}).catch(e=>{console.error(e.stack);process.exitCode=1;});
