'use strict';
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert'),Module=require('module');
const root=process.cwd(),dir=__dirname,loaderPath=path.join(root,'foundation/ConfigLoader.js'),settingsPath=path.join(root,'config/settings.json');let disk=fs.readFileSync(settingsPath,'utf8');
const fakeFs=Object.create(fs);fakeFs.readFileSync=(file,...args)=>path.resolve(String(file))===settingsPath?disk:fs.readFileSync(file,...args);
function evaluate(source,file,overrides){const m={exports:{}};const req=Module.createRequire(file);vm.runInThisContext('(function(require,module,exports,__filename,__dirname,console){'+source+'\n})',{filename:file})(id=>Object.hasOwn(overrides,id)?overrides[id]:req(id),m,m.exports,file,path.dirname(file),{log(){},warn(){},error(){}});return m.exports;}
const loader=evaluate(fs.readFileSync(path.join(dir,'candidate.js'),'utf8'),loaderPath,{'fs':fakeFs,'../core/AtomicWrite':{writeJsonAtomic(file,value){assert.equal(file,settingsPath);disk=JSON.stringify(value);}}});loader.load();

const Donchian=require(path.join(root,'modules/DonchianBreakout'));const retained=new Donchian(loader.get('strategies.DonchianBreakout'));
let saves=0,rejections=0;function save(changes){const r=loader.getSettingsView().configuration;return loader.saveSettings({requestId:'donchian-proof-'+saves++,expectedRevision:r.settings,expectedSettingsHash:r.settingsHash,changes});}
const full=k=>'strategies.DonchianBreakout.'+k,keys=['entryPeriod','atrPeriod','atrStopMult','trailChannelBars'];
const candles=Array.from({length:100},(_,i)=>({o:100,h:101,l:99,c:100,v:10,t:i*60000}));candles.push({o:100,h:104,l:99,c:103,v:10,t:6000000});
const signal=()=>retained.evaluate({priceHistory:candles},loader.get('strategies.DonchianBreakout'));
assert.equal(save({[full('entryPeriod')]:10,[full('atrPeriod')]:5,[full('atrStopMult')]:2,[full('trailChannelBars')]:7}).success,true);const first=signal();assert.equal(first.direction,'buy');assert.equal(first.exitContractHint.atrPeriod,5);assert.equal(first.exitContractHint.trailChannelBars,7);
assert.equal(save({[full('entryPeriod')]:20,[full('atrPeriod')]:8,[full('atrStopMult')]:3,[full('trailChannelBars')]:9}).success,true);const second=signal();assert.equal(retained.entryPeriod,20);assert.equal(second.exitContractHint.atrPeriod,8);assert.equal(second.exitContractHint.atrStopMult,3);assert.equal(second.exitContractHint.trailChannelBars,9);assert.notEqual(first.exitContractHint.stopLossPercent,second.exitContractHint.stopLossPercent);
const valid=disk;for(const key of keys)for(const value of [null,true,false,[],[1],{},'', ' ', 'bad',-1,0]){const c=JSON.parse(valid);c.strategies.DonchianBreakout[key]=value;disk=JSON.stringify(c);const owner=loader.getCachedSnapshot();assert.equal(loader.load({force:true}).success,false);assert.strictEqual(loader.getCachedSnapshot(),owner);assert.equal(signal().exitContractHint.atrPeriod,8);rejections++;}
for(const key of ['entryPeriod','atrPeriod']){const c=JSON.parse(valid);c.strategies.DonchianBreakout[key]=1.5;disk=JSON.stringify(c);assert.equal(loader.load({force:true}).success,false);rejections++;}
for(const value of [null,true,[],{},'', '3']){const before=disk;assert.equal(save({[full('atrPeriod')]:value}).success,false);assert.equal(disk,before);rejections++;}
const c=JSON.parse(valid);c.strategies.DonchianBreakout.entryPeriod='15';c.strategies.DonchianBreakout.atrPeriod='6';disk=JSON.stringify(c);loader.load({force:true});assert.equal(signal().exitContractHint.atrPeriod,6);assert.equal(retained.entryPeriod,15);
fs.writeFileSync(path.join(dir,'proof.json'),JSON.stringify({saves,rejections,first:first.exitContractHint,second:second.exitContractHint,finalPeriod:retained.atrPeriod,limits:'Actual save/reload and retained Donchian module with actual IndicatorCalculator, synthetic candles; disk writes intercepted in memory. No broker/full orchestrator/provider/runtime. Non-numeric configuration invariants and initial malformed startup unchanged.'},null,2)+'\n');console.log('Donchian publication proof passed');
